import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppThemeProvider from "@/shared/components/layout/theme/AppThemeProvider";
import clsx from "clsx";
import Sidebar from "@/shared/components/layout/sidebar/Sidebar";
import ToastProvider from "@/shared/components/common/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppThemeProvider>
          {/* <div className={clsx("flex", "h-dvh overflow-hidden")}>
            <Sidebar />
            <main className={clsx("2xl:flex-7  xl:flex-6 lg:flex-5 md:flex-4 sm:flex-3 flex-1", "p-2", "min-hh-dvh overflow-y-auto")}>
              {children}
            </main>
          </div> */}
          {children}
          <ToastProvider />
        </AppThemeProvider>
      </body>
    </html>
  );
}
